name: mandoob
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.3
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^9.0.0
  get_it: ^8.0.3
  shared_preferences: ^2.3.5
  simple_circular_progress_bar: ^1.0.2
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.2.0+3
  dio: ^5.7.0
  json_serializable: ^6.9.2
  json_annotation: ^4.9.0
  build_runner: ^2.4.14
  retrofit: ^4.4.2
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  pretty_dio_logger: ^1.4.0
  retrofit_generator: ^9.1.7
  flutter_secure_storage: ^9.2.4
  loading_indicator: ^3.1.1
  geocoding: ^3.0.0
  geolocator: ^9.0.2
  internet_connection_checker_plus: ^2.7.0
  connectivity_plus: ^6.1.2
  url_launcher: ^6.3.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.2"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/appIcon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icons/appIcon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/


  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: assets/fonts/Pacifico-Regular.ttf
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #   - family: Saira
  #     fonts:
  #       - asset: assets/fonts/SairaCondensed-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
